---

- name: Test S3 Interaction
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/aws.yml
    - group_vars/bitbucket.yml
    - group_vars/validate_yaml.yml
  roles:
    - validate_yaml_file