---
- name: Clone bitbucket repo
  git:
    repo: "{{ bitbucket_repo_url }}"
    dest: "{{ bitbucket_local_path }}"
    clone: yes
  register: bitbucket_repo

- name: Checkout the base branch
  git:
    repo: "{{ bitbucket_repo_url }}"
    dest: "{{ bitbucket_local_path }}"
    version: "{{ bitbucket_base_branch }}"
    force: yes

- name: Add file
  copy:
    content: |
      "String"
    dest: "{{ bitbucket_local_path }}/output/new_file.txt"
  register: new_file

- name: Commit and push to Bitbucket
  git:
    repo: "{{ bitbucket_repo_url }}"
    dest: "{{ bitbucket_local_path }}"
    src: "{{ new_file.dest }}"
    remote: origin
    version: "{{ bitbucket_branch_to_commit }}"
    force: yes
    commit_msg: "{{ bitbucket_commit_message }}"
    push: yes