---
- name: Clone bitbucket repo
  git:
    repo: "{{ bitbucket_repo_url }}"
    dest: "{{ bitbucket_local_path }}"
    clone: yes
  register: bitbucket_repo

- name: Checkout the base branch
  git:
    repo: "{{ bitbucket_repo_url }}"
    dest: "{{ bitbucket_local_path }}"
    version: "{{ bitbucket_base_branch }}"
    force: yes

- name: Add file
  copy:
    content: |
      "String"
    dest: "{{ bitbucket_local_path }}/output/new_file.txt"
  register: new_file

- name: Commit changes
  command: git commit -am "{{ bitbucket_commit_message }}"
  args:
    chdir: "{{ bitbucket_local_path }}"
  register: commit_result
  changed_when: commit_result.rc != 0

- name: push changes to bitbucket
  command: git push origin "{{ bitbucket_branch_to_commit }}"
  args:
    chdir: "{{ bitbucket_local_path }}"