---
- name: execute inline script
  command:
    cmd: usr/bin/python3
    stdin: |
      print("hello")
  register: result

- debug:
    msg: "{{ result }}"

- name:
  become: yes
  shell: "pip3 install structlog cerberus pyyaml"
  register: pip_output
  ignore_errors: true

- name: Run FileValidator script
  script:
    cmd: /scripts/text_validator.py
    executable: usr/bin/python3"

- name: Show output of FileValidator script
  debug:
    msg: "{{ file_validator_output }}"