---
- name: Run FileValidator script
  command: >
    python3 "../files/file_validator.py"
    --schema-path="../files/cerberus_schema.yml"
    --file-path="test5.yml"
    --destination="output"
  register: file_validator_output

- name: Show output of FileValidator script
  debug:
    msg: "{{ file_validator_output.stdout_lines }}"