---
- name:
  become: yes
  shell: "pip3 install structlog cerberus pyyaml"
  register: pip_output
  ignore_errors: true

- name: Run FileValidator script
  shell: "python3 scripts/file_validator.py --schema-path=cerberus_schema/cerberus_schema.yml --file-path=test5.yml --destination=output"
  register: file_validator_output

- name: Show output of FileValidator script
  debug:
    msg: "{{ file_validator_output }}"