---
- name:
  become: yes
  shell: "pip3 install structlog cerberus pyyaml"
  register: pip_output
  ignore_errors: true

- name: debugging
  debug:
    msg: "{{ schema_path }} | {{ data_path }} | {{ save_path }}"

- name: Convert Windows paths to Unix paths
  win_to_unix:
    paths:
      - "{{ schema_path }}"
      - "{{ data_path }}"
      - "{{ save_path }}"
  register: converted_paths

- name: debugging
  debug:
    msg: "{{ converted_paths.paths[0] }} {{ converted_paths.paths[1] }} {{ converted_paths.paths[2] }}"


- name: Run validation script
  script: scripts/file_validator2.py "{{ converted_paths.paths[0] }} {{ converted_paths.paths[1] }} {{ converted_paths.paths[2] }}
  register: file_validator_output

- name: Show output of FileValidator script
  debug:
    msg: "{{ file_validator_output }}"