---

- name: Download file from S3 bucket
  block:

    - name: Download file from s3
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        region: "{{ aws_region }}"
        mode: list
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
      register: s3_download_result

  rescue:
    - name: Log error message
      debug:
        msg: "Failed to download file from S3 bucket: {{ s3_download_result.msg }}"
