---

- name: Download file from S3 bucket
  block:

    - name: List files from S3 bucket
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        region: "{{ aws_region }}"
        mode: list
        access_key: "{{ aws_access_key_id }}"
        secret_key: "{{ aws_secret_access_key }}"
      register: s3_download_result

    - name: debug
      debug:
        msg: "all good"

    - name: Download a file from S3 bucket
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket_name }}"
        region: "{{ aws_region }}"
        object: "{{ s3_file_name }}"
        dest: "{{ s3_file_name }}"
        mode: get
        access_key: "{{ aws_access_key_id }}"
        secret_key: "{{ aws_secret_access_key }}"
        validate_certs: false
      register: result

    - name: debug
      debug:
        msg: "{{ result.msg }}"
      when: result.changed

  rescue:
    - name: Log error message
      debug:
        msg: "Failed to download file from S3 bucket: {{ s3_download_result.msg }}"
